### ISSUE TITLE
Set up blog with gatsby

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-blog#1]
- Functional review: @acka47
- Code review: @sroertgen

**Comment by sroertgen** [comment]
I could review the code if wanted

**Comment by acka47** [comment]
> I could review the code if wanted

Great, thanks, I added you abiove. It won't be a lot to review anyway. @katauber will set it up similar to https://github.com/metafacture/metafacture-blog.

**Comment by acka47** [comment]
From https://github.com/skohub-io/skohub.io/issues/15:

> It should be running at https://blog.skohub.io. ~~I suggest using Hugo , see https://gohugo.io/hosting-and-deployment/hosting-on-github/~~
>
> We should copy the [previous posts from lobid blog](https://blog.lobid.org/tags/skohub) and add a `link rel="canonical"`  statement to both versions for the hypothes.is annotaitons, see https://web.hypothes.is/help/how-hypothesis-interacts-with-document-metadata/#link-relcanonical.

**Comment by katauber** [comment]
@acka47 please review.
Clone with branch 1-SetUpInitialBlog:
`git clone -b 1-SetUpInitialBlog git@github.com:skohub-io/skohub-blog.git`
and follow the instructions in the README.md to install and build the gatsby blog.
Feel free to change the contents of the blog.

**Comment by fsteeg** [comment]
@acka47 has reviewed here: https://github.com/skohub-io/skohub-blog/pull/2#issuecomment-878190942
