### ISSUE TITLE
Publish blog with GitHub pages

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-blog#3]
See https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/ for instructions on how to use gatsby with GitHub pages.

I think, we should
- publish to the root subdomain 
- configure a reverse proxy so that post are published at https://blog.skohub.io

Functional review: @acka47 
Code review: @fsteeg

**Comment by acka47** [comment]
We decided to first publish to https://skohub-io.github.io and then set up the reverese proxy in a next step.

**Comment by dr0i** [comment]
@dr0i : 
- [ ] configure proxy.

**Comment by dr0i** [comment]
Configured as proxy, note the missing certificate. While it looks ok, it is not: look in the browser's dev console for missing files. E.g. the file `https://blog.skohub.io/skohub-blog/favicon-32x32.png?v=91b1901e405e1500f9b7569b85f1ad60` is missing while it works leaving out the `/skohub-blog`, see `https://blog.skohub.io/favicon-32x32.png?v=91b1901e405e1500f9b7569b85f1ad60` . That's because of the proxy. It _would_ be fixed if we could assure  ` https://skohub-io.github.io/`  to work (as claimed in https://github.com/skohub-io/skohub-blog/issues/3#issuecomment-905372910), not `https://skohub-io.github.io/skohub-blog/` as it is atm.

**Comment by dr0i** [comment]
note to self: may be the same problem as in https://github.com/metafacture/metafacture-playground/issues/27. Check that out.

**Comment by dr0i** [comment]
@acka47 forked, branched and deployed to [my pages}( https://dr0i.github.io/skohub-blog/) to test the setup. I think it's fine now with the `pathPrefix` removed. If you check the links: they lack the `"/skohub-blog` part.

**Comment by dr0i** [comment]
Also configured this setup into the proxy - test it : https://blog.skohub.io/ .

**Comment by acka47** [comment]
Looks fine. The `rel=canonical` links should be configured differently, though. Currently they are pointing to GitHub pages, e.g. at https://blog.skohub.io/2020-10-09-skohub-apconf/: `<link rel="canonical" href="https://skohub-io.github.io/skohub-blog/2020-10-09-skohub-apconf/"`. This should be `<link rel="canonical" href="https://blog.skohub.io/2020-10-09-skohub-apconf/"` instead. Maybe we could use https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/ for this. Assigning @katauber .

**Comment by katauber** [comment]
> Looks fine. The `rel=canonical` links should be configured differently, though. Currently they are pointing to GitHub pages, e.g. at https://blog.skohub.io/2020-10-09-skohub-apconf/: `<link rel="canonical" href="https://skohub-io.github.io/skohub-blog/2020-10-09-skohub-apconf/"`. This should be `<link rel="canonical" href="https://blog.skohub.io/2020-10-09-skohub-apconf/"` instead. Maybe we could use https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/ for this. Assigning @katauber .

This plugin is already installed, I will adjust the gatsby-conf.js to the right url.

**Comment by dr0i** [comment]
Merged #6 into main to trigger a rebuild of the pages.
Reopening this issue for functional review.

**Comment by dr0i** [comment]
Hm , wait @acka47 with your review, it seems like the canonical links are not fixed yet. Investigating...

**Comment by dr0i** [comment]
(Proxy was set to my dr0i test repo. Ok to review now @acka47

**Comment by acka47** [comment]
+1 Looks good to me. We will announce the blog as soon as the SSL certificate is installed. (You could also sign it in a video conference and then bring it to hbz next week, @dr0i .)

**Comment by dr0i** [comment]
Installed SSL certifictates. You may want to ckeck @acka47 .

**Comment by acka47** [comment]
+1 Looks good. Unfortunately, hypothes.is annotations are not shown at neither of the blogs now. I opened another issue for this at #7 .

**Comment by acka47** [comment]
Closing.
